server:
  port: 8585

application:
  max-allowed-books: 2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ui-service

logging:
  enabled: true
  log-body: true
  log-level: warn
