server:
  port: 8686

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

spring:
  application:
    name: reporter